### ISSUE TITLE
bug: The useWalletClient() hook returns undefined after opening the application in a new tab while using MetaMask. 

### ISSUE THREAD

**Issue by kuji2336** [wevm/wagmi#2784] opened 2023-07-21 08:46 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.3.9

### Current Behavior

After connecting to the application with the MetaMask wallet using the browser and attempting to open the app in a different tab multiple times, the `useWalletClient()` hook randomly returns `undefined`. but MetaMask shows that wallet is connected, it's even possible to retrieve connected account address.
However, after refreshing the page, the `useWalletClient()` hook starts behaving correctly.

### Expected Behavior

Every time when user opens tab `useWalletClient()` should return data when wallet is connected.

Expected behavior is correct for "WalletConnect" provider.

### Steps To Reproduce

1.Connect your MetaMask Wallet to application (Link Below)
2.You can see `useWalletClient()` data been printed.
3.Try to open application in different tab multiple time (As it described in below video)
4.Randomly` useWalletClient()` data is undefined, and wallet is still connected

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://sandbox-snowy-ten.vercel.app/

### Anything else?

SandBox: [url](https://codesandbox.io/p/sandbox/sleepy-mcnulty-5v99gn?file=%2Fpages%2F_app.tsx%3A22%2C4)

https://github.com/wagmi-dev/wagmi/assets/58769030/f033c6ed-1758-473c-be41-84a799c088ff

**Comment by Alonsso** [comment] 2023-07-26 20:19
I am having the same issue, but for some reason it is not returning `WalletClient` type. Instead, I am getting a `GetWalletClientResult` type. However, when I try to call `getAdresses()` from `useWalletClient()` hook, response is undefined. 😒

Wagmi 1.3.9
Viem 1.4.1

**Comment by kristiegiles** [comment] 2023-08-01 20:50
I have the same issue

<img width="359" alt="Screenshot 2023-07-11 at 11 16 35 PM" src="https://github.com/wagmi-dev/wagmi/assets/25679998/9767d518-1c0f-4fc9-ab3d-388a0ad0e16f">

**Comment by Alonsso** [comment] 2023-08-02 01:48
> I have the same issue.
> 
> <img alt="Screenshot 2023-07-11 at 11 16 35 PM" width="359" src="https://user-images.githubusercontent.com/25679998/257638230-9767d518-1c0f-4fc9-ab3d-388a0ad0e16f.png">

I had to use the next action from `@wagmi/core` [https://wagmi.sh/core/actions/getWalletClient](url)

**Comment by kristiegiles** [comment] 2023-08-04 20:39
I had to use the next action from @wagmi/core [https://wagmi.sh/core/actions/getWalletClient](https://github.com/wagmi-dev/wagmi/issues/url)

```
import { getWalletClient } from 'wagmi/actions';
```
and 
```
const walletClient = await getWalletClient();
```

before calling methods on the walletClient didn't seem to resolve the issue for me, the walletClient is still undefined

**Comment by jalagar** [comment] 2023-09-19 03:33
Also having the same issue 🙏

**Comment by glitch-txs** [comment] 2023-09-19 03:49
This should fix the issue
https://wagmi.sh/react/connectors/metaMask#unstable_shimonconnectselectaccount

**Comment by glitch-txs** [comment] 2023-09-19 03:54
Haven't look deep into this one yet, but I feel it might be related to manifest v3, this should be fixed in Wagmi v2. [See issue](https://github.com/wagmi-dev/references/issues/167)

**Comment by glitch-txs** [comment] 2023-09-19 03:57
> I had to use the next action from @wagmi/core [https://wagmi.sh/core/actions/getWalletClient](https://github.com/wagmi-dev/wagmi/issues/url)

Switching from using useWalletClient to

import { getWalletClient } from 'wagmi/actions';
and

const walletClient = await getWalletClient();
before calling methods on the walletClient didn't seem to resolve the issue for me, the walletClient is still undefined

@kristiegiles have you try this action inside a useEffect hook?

**Comment by kristiegiles** [comment] 2023-10-23 17:50
> > I had to use the next action from @wagmi/core [https://wagmi.sh/core/actions/getWalletClient](https://github.com/wagmi-dev/wagmi/issues/url)
> > Switching from using useWalletClient to
> > import { getWalletClient } from 'wagmi/actions';
> > and
> > const walletClient = await getWalletClient();
> > before calling methods on the walletClient didn't seem to resolve the issue for me, the walletClient is still undefined
> 
> @kristiegiles have you try this action inside a useEffect hook?

I was doing it inside an onClick callback. For example,
```
  const signMessage = useCallback(async (data: string) => {
    const walletClient = await getWalletClient();
    const signature = await walletClient.signTypedData(JSON.parse(data));
    // ...
  }, []);
```

**Comment by siosio34** [comment] 2023-11-21 01:16
This issue is occurring to me too

**Comment by Magvin** [comment] 2023-11-23 12:52
+1 here

**Comment by kuji2336** [comment] 2023-11-23 21:40
This problem still exists in the latest version of Wagmi. I was using Rainbowkit as a connector provider, so in my Next.js application, I encountered weird UI effects. The wallet state was showing as connected, but the connector was undefined when using the useAccount() hook. To avoid the aforementioned weird behavior for now, I am simply checking if the connector instance exists. Otherwise, I am manually disconnecting the wallet, so the user should reconnect, btw I could not find proper solution


```
const { connector } = useAccount()

useEffect(() => {
    if (!connector?.name) {
      disconnect()
    }
 }, [connector])
```

**Comment by Magvin** [comment] 2023-11-24 07:23
Apparently we have fixed it with  `provider.connect()` then grab result and setState of storage

**Comment by siosio34** [comment] 2023-11-24 08:15
@Magvin  Can you show me some example code?

**Comment by Magvin** [comment] 2023-11-24 08:18
> @Magvin Can you show me some example code?


const handleConnect = useCallback(async () => {
		if (address) return
		try {
			const result = await metaMaskConnector?.connect()
			config.store?.setState(prevState => ({
				...prevState,
				data: result,
				status: 'reconnecting',
			}))
		} catch {
			/**
			 * Don't do anything
			 */
		}
}, [metaMaskConnector, address])

**Comment by paintoshi** [comment] 2023-12-07 18:49
I had the same issue ever since I started to use wagmi. Use it together with the web3modal. Opening the app in a new tab works fine, wagmi re-connects and the getWalletClient() returns the client as it should. But if I close the tab, change the account in the wallet (metamask or rabby), then open a new tab with the app, wagmi will return the old account (useAccount()) and think it's still connected. But the getWalletClient() will return null since the client is now broken. Any wallet call will fail, and user can't connect even if I force disconnect. The only way around it is to refresh the page and then the app will auto connect to the new account.

I can't figure out how to have wagmi auto-connect to the new account. I think the same thing happens if you switch network.

**Comment by kristiegiles** [comment] 2023-12-08 00:02
> This problem still exists in the latest version of Wagmi. I was using Rainbowkit as a connector provider, so in my Next.js application, I encountered weird UI effects. The wallet state was showing as connected, but the connector was undefined when using the useAccount() hook. To avoid the aforementioned weird behavior for now, I am simply checking if the connector instance exists. Otherwise, I am manually disconnecting the wallet, so the user should reconnect, btw I could not find proper solution
> 
> ```
> const { connector } = useAccount()
> 
> useEffect(() => {
>     if (!connector?.name) {
>       disconnect()
>     }
>  }, [connector])
> ```

This is similar to what I ended up doing, except in my case the connector is set and only the walletClient is not defined.
Here's a simplified version:

```
  const { isConnected, connector } = useAccount();
  const { data: walletClient, isLoading: isLoadingWalletClient } = useWalletClient();
  const { disconnect } = useDisconnect();

  useEffect(() => {
    if (isConnected && connector !== undefined && !isLoadingWalletClient && !walletClient) {
      disconnect();
    }
  }, [ isConnected, connector, isLoadingWalletClient, walletClient ]);

**Comment by kristiegiles** [comment] 2023-12-08 00:21
> But the getWalletClient() will return null since the client is now broken. Any wallet call will fail, and user can't connect even if I force disconnect. The only way around it is to refresh the page and then the app will auto connect to the new account.

You may be able to use `!isLoadingWalletClient && !walletClient` (from `const { data: walletClient, isLoading: isLoadingWalletClient } = useWalletClient();`) to determine that you need to refresh the app, since isLoading will be true while it loads the walletClient on initial render. In my case, I added some extra checks and ended up with something like  `if (isConnected && address !== undefined && connector !== undefined && !isLoadingWalletClient && !walletClient)` to minimize unnecessary force disconnecting. I am not using web3modal, but after force disconnecting and clicking to reconnect manually, the walletClient methods start working again for me with no refresh.

**Comment by paintoshi** [comment] 2023-12-08 09:37
> You may be able to use `!isLoadingWalletClient && !walletClient` (from `const { data: walletClient, isLoading: isLoadingWalletClient } = useWalletClient();`) to determine that you need to refresh the app, since isLoading will be true while it 

So this kind of works for me. It does disconnect the user when the connection is invalid. But the difference for me is that the user can't connect again when doing this. The `connect({ connector: injected })` does absolutely nothing, until they refresh the app and then it works again for some reason. The "injected" in this case is `connectors.find((connector) => connector.id === 'injected')` since I'm dealing with multiple types. I've inspected the "injected" connector and it looks identical in both cases.

The best for me would be to tell the user to refresh the app, but can't use the method you described because it will be called even for valid sessions. I'm pretty sure it does that for you too, disconnecting just before it connects. If you put a console.log before your `disconnect()`.

I will spend more time trying to figure out why the connector is not initialized on page open, but is on page refresh. That would be the real fix.

**Comment by uniquesyl** [comment] 2024-01-03 02:28
+1 here

**Comment by tmm** [comment] 2024-01-05 16:30
We have moved on to Wagmi v2. Feel free to re-open this with a minimal reproduction if this still exists there.

**Closed by tmm** 2024-01-05 16:30 UTC
