### ISSUE TITLE
Multiple Issues with Injected Connectors

### ISSUE THREAD

**Issue by frankfka** [wevm/wagmi#3526] opened 2024-01-26 20:13 UTC
### Describe the bug

This list isn't by any means exhaustive, but I've noticed multiple issues with lesser-known wallets when connecting via `wagmi` that do _not_ occur with wagmi 1.x

**OKX Wallet**
- Once connected, disconnecting does not work

**Trust Wallet**
- Attempting to connect results in an error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/nextjs-apz8ps?file=app%2FProviders.tsx

### Steps To Reproduce

With OKX Wallet - try to connect and disconnect
With trust wallet - try to connect

### Wagmi Version

2.5.4

### Viem Version

2.5.0

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment] 2024-01-26 20:54
Not sure if this is the same case with OKX Wallet, but looks like Trust Wallet doesn't implement `removeListener`, which is a [required EIP-1193 event handling method.](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-1193.md#events) This would explain why it fails connecting [here](https://github.com/wevm/wagmi/blob/main/packages/core/src/connectors/injected.ts#L182). This happens in v2 because we try to clean up some events that we didn't in v1.

**Comment by tmm** [comment] 2024-01-26 21:06
@frankfka can you try `wagmi@canary` and see if it's fixed?

**Comment by glitch-txs** [comment] 2024-01-26 21:13
> looks like Trust Wallet doesn't implement removeListener

I reported this in December, I'll reping them 🙈

**Comment by frankfka** [comment] 2024-01-26 21:45
> @frankfka can you try `wagmi@canary` and see if it's fixed by [2a72214](https://github.com/wevm/wagmi/commit/2a72214a2901d6b6ddd39f80238aa0bd4db670a7)?

Nice! That worked for Trust, the OKX Disconnect issue is still there

**Comment by tmm** [comment] 2024-01-26 22:01
What's the issue? Error message, etc. would be helpful.

**Comment by frankfka** [comment] 2024-01-26 22:05
> What's the issue? Error message, etc. would be helpful.

There's no error, but disconnecting doesn't work:

https://github.com/wevm/wagmi/assets/31530056/e7b27ae2-1077-4424-babc-68e17f1f33e0

**Comment by tmm** [comment] 2024-01-26 22:06
Works fine for me when connecting and disconnecting.

https://github.com/wevm/wagmi/assets/6759464/1c518697-039b-49a1-b11a-8c0a9bf236d7

**Comment by frankfka** [comment] 2024-01-26 22:10
Hmm that's odd.. I'm getting the behavior I sent in the stackblitz link

**Comment by W3stside** [comment] 2024-01-27 08:44
@frankfka this is happening for me as well w/injected. It fails in local and seems to be a `wagmi.store` issue. I'm not exactly sure what it is but it seems to happen more often non-deterministically when running several tabs with wagmi providers.

In production this never happens, or at least it never does after clearing cache and hard reloading hence why I think it's an issue with the local storage `wagmi.store`

**Comment by tmm** [comment] 2024-01-30 20:17
Closing as fixed by https://github.com/wevm/wagmi/commit/2a72214a2901d6b6ddd39f80238aa0bd4db670a7 since I'm [not able to reproduce](https://github.com/wevm/wagmi/issues/3526#issuecomment-1912757804).

**Closed by tmm** 2024-01-30 20:17 UTC
