### ISSUE TITLE
writeContract error functionName from generated.ts

### ISSUE THREAD

**Issue by arthurneuron** [wevm/wagmi#3620] opened 2024-02-21 11:18 UTC
### Describe the bug

Generated file from foundry:
```javascript
/**
 * Wraps __{@link useWriteContract}__ with `abi` set to __{@link contractAbi}__ and `functionName` set to `"newWorld"`
 *
 *
 */
export const useWriteContractNewWorld = /*#__PURE__*/ createUseWriteContract({
  abi: staqeAbi,
  address: contractAddress,
  functionName: 'newWorld',
})
```

App.tsx file app:
```javascript
  const { writeContract } = useWriteContractNewWorld()
  const onClick = React.useCallback(() => {
    writeContract({
      functionName: 'newWorld',
      args: [],
    })
  }, [writeContract])
```

`Object literal may only specify known properties, and 'functionName' does not exist in type`

Without `functionName` in `writeContract ` function not work.

### Wagmi Version

latest

### Viem Version

latest

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by tmm** [comment] 2024-02-21 14:35
Duplicate of https://github.com/wevm/wagmi/issues/3613, will be fixed by https://github.com/wevm/wagmi/pull/3623

**Closed by tmm** 2024-02-21 14:35 UTC
